image: Visual Studio 2017

build: off

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" ..
  - msbuild sds-lk.sln /property:Configuration=RelWithDebInfo /target:sds-test
  - .\RelWithDebInfo\sds-test.exe
